---

#file: /roles/dependencies/tasks/main.yml

- name: install packages
  apt: name={{item}} state=present
  with_items:
    - git
    - nmap
    - vim
    - curl
    - wget
    - strace
    - nmap
    - net-tools
    - unzip
